name: flutter_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  google_maps_flutter: ^1.0.2
  flutter_local_notifications: ^2.0.0+1
  cupertino_icons: ^1.0.0
  photo_view: ^0.10.2
  image_picker: ^0.6.7+11
  font_awesome_flutter: ^8.10.0
  flushbar: ^1.10.4
  fluttertoast: ^7.1.1
  sliding_up_panel: ^1.0.2
  flutter_datetime_picker: ^1.4.0


  # ARCHITECTURE
  rxdart: ^0.24.1
  provider: ^4.3.2
  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2
  get_it: ^4.0.4
  flutter_translate: ^1.6.0



  # FIREBASE
  firebase_auth: ^0.18.2
  firebase_analytics: ^6.1.0
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.2
  google_sign_in: ^4.5.5
  #  geoflutterfire: ^2.1.0
  firebase_database: ^4.2.0
  firebase_core: ^0.5.1
  firebase_dynamic_links: ^0.6.1
  firebase_remote_config: ^0.4.1

  # UTILS
  built_value: ^7.1.0
  flutter_cache_manager: ^1.4.2
  location: ^3.0.2
  connectivity: ^0.4.9+3
  shared_preferences: ^0.5.12
  device_info: ^0.4.2+6
  app_settings: ^4.0.3
  cached_network_image: ^2.3.2+1
  logger: ^0.9.4
  hashids2: ^1.0.3
  faker: ^1.2.1
  validators: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  built_value_generator: ^7.1.0
  build_runner: ^1.10.2
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1



flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/images/img_not_available.jpeg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
